### ISSUE TITLE
検索を高速化

### ISSUE THREAD

**Issue by wakamenori** [wakamenori/yuru-corpus-backend#48]

**Comment by wakamenori** [comment]
# **Opensearchにローカルから接続できない問題**

# 結論
Lambdaにデプロイしたら動いたので、一旦ローカルでの実行は諦めて実装する。
デプロイが遅いのが致命的なので早く #36 をやった方がいい。

# 発生している問題
ローカルで立てたFlaskAPIからOpensearch serverlessにリクエストを送ったが、エラーが発生。
AWSコンソール内のOpensearch ダッシュボードにログインする時と同じIAMユーザーでアクセスしているはずなのに、ローカルからのアクセスは失敗するので不可解。

## APIのコード(一部省略)
インデックス作成、検索の2パターン試したが、それぞれで同じエラーが発生した。

コードを拾ってきたのは[Amazon OpenSearch Serverless(プレビュー) にPythonスクリプトからデータ投入をしてみました
](https://www.skyarch.net/blog/?p=23056)だが、基本的にserverless ではないOpenSearchの公式Doc[Ingesting data into Amazon OpenSearch Serverless collections Python](https://docs.aws.amazon.com/opensearch-service/latest/developerguide/serverless-clients.html#serverless-python)のサンプルコードとほとんど同じ。
差分は`service = "es"`ではなく`service = "aoss"`なことくらい。
`aoss`は`AmazonOpenSearchServerless`から来ている？IAMポリシーも`aoss:CreateCollection`などとなっているし、この値は間違っていないと思う。

```py
from opensearchpy import AWSV4SignerAuth, OpenSearch, RequestsHttpConnection
from requests_aws4auth import AWS4Auth

@bp.route("/opensearch", methods=["GET"])
def lambda_handler():
    search_string = request.args.get("string", None)
    host = "**********************.ap-northeast-1.aoss.amazonaws.com"  # 一応伏せ字にしたけど、本来は20字くらいの文字列
    region = "ap-northeast-1"
    service = "aoss"
    credentials = boto3.Session().get_credentials()
    awsauth = AWS4Auth(
        credentials.access_key,
        credentials.secret_key,
        region,
        service,
        session_token=credentials.token,
    )
    client = OpenSearch(
        hosts=[{"host": host, "port": 443}],
        http_auth=awsauth,
        use_ssl=True,
        verify_certs=True,
        connection_class=RequestsHttpConnection,
    )

    # インデックスを作成
    index_name = 'my-index'
    index_body = {
        "mappings": {
            "properties": {
                "title": {"type": "text"},
                "director": {"type": "text"},
                "year": {"type": "integer"}
            }
        }
    }
    response = client.indices.create(index_name, body=index_body)  # ここでエラー

    # 検索してみる
    query = {"query": {"match_all": {}}}
    index_name = "dev"
    response = client.search(body=query, index=index_name)  # ここでエラー
    return response
```
## エラーメッセージ
```text
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.9/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/user/.local/lib/python3.9/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/home/user/.local/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/user/.local/lib/python3.9/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/user/.local/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/user/.local/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/user/.local/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/user/.local/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/user/.local/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/user/.local/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/user/.local/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/user/.local/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/search_api/api.py", line 131, in lambda_handler
    response = client.indices.create(index_name, body=index_body)
  File "/home/user/.local/lib/python3.9/site-packages/opensearchpy/client/utils.py", line 178, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  File "/home/user/.local/lib/python3.9/site-packages/opensearchpy/client/indices.py", line 128, in create
    return self.transport.perform_request(
  File "/home/user/.local/lib/python3.9/site-packages/opensearchpy/transport.py", line 408, in perform_request
    raise e
  File "/home/user/.local/lib/python3.9/site-packages/opensearchpy/transport.py", line 369, in perform_request
    status, headers_response, data = connection.perform_request(
  File "/home/user/.local/lib/python3.9/site-packages/opensearchpy/connection/http_requests.py", line 210, in perform_request
    self._raise_error(
  File "/home/user/.local/lib/python3.9/site-packages/opensearchpy/connection/base.py", line 301, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(
opensearchpy.exceptions.AuthorizationException: AuthorizationException(403, 'security_exception', "OpenSearch exception [type=authorization_exception, reason=User don't have permission for requested resource.]")
```

# APIでエラーになる前に、Opensearch serverlessのセットアップとしてやったこと
[チュートリアル](https://docs.aws.amazon.com/opensearch-service/latest/developerguide/serverless-getting-started.html)に従ってコレクションを作成した。

## チュートリアルの内容
1. [Configure permissions (IAM)](https://docs.aws.amazon.com/opensearch-service/latest/developerguide/serverless-getting-started.html#serverless-gsg-permissions)
    > Administrator権限を持ったアカウントを使っている(よく無い)ので関係なし。
2. [Create a collection (コレクションの作成)](https://docs.aws.amazon.com/opensearch-service/latest/developerguide/serverless-getting-started.html#serverless-gsg-create)
    > コレクションの名前以外はチュートリアルと同じ
コレクション=従来のクラスター?
3. [Configure data access (データアクセスポリシーの設定)](https://docs.aws.amazon.com/opensearch-service/latest/developerguide/serverless-getting-started.html#serverless-gsg-data)
    > 基本的に名前以外はチュートリアルと同じ。
    > 上記のAdministrator権限を持ったアカウントに加え、検索APIのLambda実行ロールにもアタッチ。
    > 8. For Specific indexes or index patterns, enter a wildcard (*).
のところで`*`を指定したが、後述するエラーが発生したため、のちに`dev`に変更した。その後、`*`に戻しても動いたため、因果関係は不明。現状は`*`を使用中。

4. [Upload and search data](https://docs.aws.amazon.com/opensearch-service/latest/developerguide/serverless-getting-started.html#serverless-gsg-index)
    > AWSコンソール内のダッシュボードに、データアクセスポリシーをアタッチしたIAMユーザーのアクセスキーIDとシークレットアクセスキーでログイン
`PUT dev/_doc`でindexを作成後、以下のようにデータ追加を試すが、`403`エラーが発生。前述のようにデータアクセスポリシーでインデックスを`*`から`dev`に変更したのち`200`で成功。

```
PUT dev/_doc
{
    "Token": "ゆる言語学ラジオ",
    "Timestamp": "1#00:00:01",
    "Speaker": "こんにちは"
}
```
5. [Delete the collection](https://docs.aws.amazon.com/opensearch-service/latest/developerguide/serverless-getting-started.html#serverless-gsg-delete)
    > 5は放置してローカルからのアクセスにトライした。


## 現状のデータアクセスポリシー
<img width="630" alt="image" src="https://user-images.githubusercontent.com/98820865/210787912-31e3fb2b-2454-4ca9-b4fa-1e9fc7aa8220.png">

## ダッシュボードからは正常に動作したよ、の図
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/98820865/210784781-f93680ba-6e2e-438a-a1f9-7d27d9360594.png">

# 試したこと
## 適切なユーザー情報をclientに与えられていないのでは無いかという仮説
エラーメッセージに`User don't have permission for requested resource.`とあるので、単純に`boto3`による認証情報の取得に失敗したのでは無いかというもの。しかし、`credentials`の中身を確認すると、正常に認証できていた。
↓当該コード
```py
credentials = boto3.Session().get_credentials()
```
## データアクセスポリシーのワイルドカード削除
`*`を`dev`に変更してみた。効果なし。

## あきらめる
Lambdaにデプロイしたら動いた(謎)ので、放置してもいいのでは？というもの。

**Comment by wakamenori** [comment]
dairappaさんのレス

> デバッグで問題絞り込んでいくなら
> 1. 同じ権限を明示的に降って挙動が変わるかみる
> 2. コンテナに権限情報ハードコーティングしてみる
> 3. LambdaのロールにSwitchするように権限変更してみる
> 
> とかかなぁ…

**Comment by wakamenori** [comment]
一旦Opensearchに移行したので高速化は完了
データの同期は #51 で
